version: '3.1'

services:

  database:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
    - ./postgresql_data:/var/lib/postgresql/data
    ports:
    - 5432:5432
  mongo:
    image: mongo:4.2.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
    - ./mongodb_data:/data/db
    ports:
    - 27017:27017