version: '3.1'

services:

  database:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
    volumes:
    - ./postgresql_data:/var/lib/postgresql/data
    ports:
    - 5432:5432